name: Schoolclock
description: an app to improve yout productivity and efficency within your learning environment.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_expandable_fab: ^1.5.2
  http: ^0.13.5
  sqflite: ^2.2.2
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  easy_splash_screen: ^1.0.4
  


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons8-digital-clock-48.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/icons8-digital-clock-96.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "lib/assets/icons8-digital-clock-96.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    

  